import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "../../packages/ui/src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary-fixed-dim": "#eec200",
        "text-primary": "#FFFFFF",
        "on-error": "#690005",
        "primary-fixed-dim": "#ffb690",
        "on-secondary-fixed-variant": "#574500",
        tertiary: "#93ccff",
        background: "#131315",
        secondary: "#ffe083",
        "on-surface": "#e5e1e4",
        "on-surface-variant": "#e0c0b1",
        "surface-variant": "#353437",
        "on-secondary-container": "#645000",
        "on-tertiary-fixed": "#001d32",
        "surface-deep": "#09090B",
        "surface-container-low": "#1c1b1d",
        "on-primary-container": "#582200",
        "tertiary-fixed": "#cde5ff",
        "on-primary-fixed-variant": "#783200",
        surface: "#131315",
        "success-green": "#22C55E",
        "surface-dim": "#131315",
        "on-primary": "#552100",
        "surface-card": "#1A1A1A",
        "tertiary-container": "#00a2f4",
        "on-secondary-fixed": "#231b00",
        primary: "#ffb690",
        "on-primary-fixed": "#341100",
        "surface-bright": "#39393b",
        "surface-tint": "#ffb690",
        "inverse-primary": "#9d4300",
        "on-tertiary-container": "#003554",
        "on-tertiary-fixed-variant": "#004b74",
        "inverse-on-surface": "#313032",
        "inverse-surface": "#e5e1e4",
        "on-background": "#e5e1e4",
        "text-muted": "#A1A1AA",
        "secondary-fixed": "#ffe083",
        "surface-container": "#201f22",
        error: "#ffb4ab",
        "primary-container": "#f97316",
        "surface-container-highest": "#353437",
        outline: "#a78b7d",
        "surface-container-high": "#2a2a2c",
        "tertiary-fixed-dim": "#93ccff",
        "error-red": "#EF4444",
        "primary-fixed": "#ffdbca",
        "on-secondary": "#3c2f00",
        "on-error-container": "#ffdad6",
        "outline-variant": "#584237",
        "error-container": "#93000a",
        "surface-container-lowest": "#0e0e10",
        "on-tertiary": "#003351",
        "secondary-container": "#eec200",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "container-max": "1280px",
        gutter: "24px",
        base: "8px",
        "margin-desktop": "40px",
        "margin-mobile": "16px",
      },
      fontFamily: {
        "body-md": ["Inter"],
        "headline-lg": ["Hanken Grotesk"],
        "label-sm": ["JetBrains Mono"],
        "display-lg": ["Hanken Grotesk"],
        "headline-lg-mobile": ["Hanken Grotesk"],
        "body-lg": ["Inter"],
        "title-md": ["Hanken Grotesk"],
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "700" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "500" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "title-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
      },
      keyframes: {
        float: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-15px)' },
        },
        pulseGlow: {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0.6' },
        }
      },
      animation: {
        float: 'float 4s ease-in-out infinite',
        'float-delayed': 'float 4s ease-in-out 2s infinite',
        'float-slow': 'float 5s ease-in-out 1s infinite',
        'pulse-glow': 'pulseGlow 3s ease-in-out infinite',
      },
    },
  },
  plugins: [],
};

export default config;
