version: '3.8'
services:
  db:
    image: postgres:15-alpine
    container_name: vthub-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: vthub
    ports:
      - '54320:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
